src/Helpers/BigOp.v

A wrong  instance involving `option unit` was found otherwise at ` intros ?%elem_of_singleton.`
It seems the SemiSet (in stdpp?) modes are not set correctly, as this declaration is necessary for an unambiguous typeclass resolution in the proof script below. I'd be happy if you could merge this fix here and later submit it to upstream so as to not delay https://github.com/coq/coq/pull/10858 any further. The fix should be backwards compatible of course.

Fix misuse of modes for SemiSet

---

src/program_logic/crash_adequacy.v
src/program_logic/recovery_adequacy.v
src/program_logic/step_fupd_extra.v

|={E1,E2}_k=>^n notation makes no sense with different masks, so force them to be the same.
I'm still new here so I figured I'd better make this a PR. ;)
@jtassarotti @tchajed do you get notifications for PRs?

|={E1,E2}_k=>^n notation makes no sense with different masks

---

src/goose_lang/lib/lock/crash_lock.v
src/goose_lang/lib/lock/lock.v
src/program_logic/na_crash_inv.v
src/program_logic/staged_invariant.v
src/program_logic/staged_wpc.v
src/program_proof/append_log_hocap.v
src/program_proof/examples/alloc_crash_proof.v
src/program_proof/examples/alloc_proof.v
src/program_proof/examples/inode_proof.v
src/program_proof/examples/replicated_block_proof.v
src/program_proof/examples/single_inode_proof.v

Basically, things that are stored in an invariant/lock should consistently just have a later in front of them when being talked about outside the invariant/lock. The crash_lock spec is even a bit stronger than that, by providing `R` (and not just `\later R`) after "acquire" -- it has the luxury of taking a step and it exposes that to its clients.
Unfortunately this makes caching work a bit less good in some places as laters occur and then go away after the next step.
I have no idea what I did to the layers below crash_inv; that is all solely based on pushing things through until Coq stops complaining...

inode, alloc: consistently keep P below one level of later

---

src/program_proof/lockservice/proof.v

@RalfJung Let me know if this makes sense to you.
I got rid of the lockservice_alloc_token, so now you can do lockservice_alloc_lock whenever you want, as long as you have the necessary P.

Remove need for lockservice_alloc_token in lockservice_is_lock witness

---

src/algebra/fmcounter.v
src/goose_lang/lib/struct/struct.v

Hi, this PR adapts to Coq PR coq/coq#13512 which makes the naming in the presence of the `%` introduction pattern compatible with name mangling. As a result, an `H0` is now named `H` in perennial's file ` src/goose_lang/lib/struct/struct.v`.
We fix the corresponding proof in a backward-compatible by not letting Coq generate the name. If you agree with the fix, it can be merged as soon as now.

Adapt to a more-principled name generation in the "%" introduction pattern

---

src/algebra/na_heap.v
src/algebra/own_discrete.v

Before the mentioned Coq PR, "rewrite foo in H *" with ssreflect
rewrite and a setoid equality would leave the goal with H reverted.
Instead we manually revert H and don't use "in".

Don't rely on ssreflect setoid rewrite bug (coq/coq#13882)

---

src/program_proof/examples/inode_proof.v

Due do coq/coq#14392, only heads of applications should not be evars for ! to match a term during typeclass resolution. This makes the iris automation more powerful, resulting in a breakage in the script.

Backward compatible fix

---

src/program_proof/examples/dir_proof.v
src/program_proof/examples/inode_proof.v

Second commit adds a similar fix needed for `dir_proof`.

For Coq PR #14392

---

Makefile

Without .glob files, it's extremely hard to support automatic minimization of build failures in perennial caused by changes in Coq's PRs.  In particular, there's no general way to both reuse the artifacts from Coq's CI and also determine the correct invocation of coqc to regenerate a .glob file for a given .v file.  I could support this build mode by blowing away any .vo files from Coq's CI which don't have corresponding .glob files and then modifying the coqc wrapper to discard `-noglob`...   However, I don't see a real reason to skip building .glob files here.

Revert a57832ec6f4a43c184151f4a962b296d0e1cc982 and remove `-noglob`

---

src/goose_lang/wpc_proofmode.v

Remove some unnecessary `crashGS` arguments. I think they are there due to the history mentioned in https://github.com/mit-pdos/perennial/pull/32#issuecomment-829330906.

Remove crashGS arguments

---

src/goose_lang/interpreter/interpreter.v

Should be backwards compatible.

Adapt to coq/coq#13837 ("apply with" does not rename arguments)

---

src/program_logic/atomic_fupd.v

Ralf wrote a comment explaining the explicit scope annotations  on Mattermost
and I thought it would make for good documentation (we might use this file in Aneris).

Add comment explaining scope annotations in atomic_fupd

---

.github/workflows/build.yml
etc/ci-goose-check.sh

Adds a little script and CI job to re-run Goose and check that `git diff` remains clean.
For now, Goose and the Go code repos are pinned to a particular commit each, but we could pin them to a branch as well.
I confirmed that before https://github.com/mit-pdos/perennial/commit/06834cebd125ceef376e547e471f80f770700f87, this indeed failed.

check on CI that Goose files are clean

---

src/program_proof/wal/recovery_proof.v

Before Coq 8.19 `replace foo with bar by tac` actually meant `replace foo with bar by first [assumption | symmetry; assumption | tac]`.

Fix incorrect "replace by"

---

src/algebra/na_heap.v

Very small deletion in src/algebra/na_heap.v.
This should be backward compatible.

Adapt wrt Coq/Coq#18164

---

.github/workflows/ci.yml
pyproject.toml
src/program_proof/pav/merkle.v
src/program_proof/pav/server.v

docker-coq-action used Python 3.11 instead of 3.9, which requires more isolation.
Also, something changed, and it appears the previous `pip install .`, which wrote some files out, now gives a permissions denied error.

Fix python venv inside docker-coq-action container

---

new/golang/theory/slice.v
src/Helpers/Integers.v
src/goose_lang/lib/rwlock/rwlock.v
src/goose_lang/lib/rwlock/rwlock_noncrash.v
src/goose_lang/lib/slice/slice.v
src/goose_lang/lib/waitgroup/waitgroup.v
src/goose_lang/proofmode.v
src/program_proof/alloc/alloc_proof.v
src/program_proof/marshal_proof.v
src/program_proof/memkv/memkv_coord_make_proof.v
src/program_proof/memkv/memkv_coord_start_proof.v
src/program_proof/memkv/memkv_shard_make_proof.v
src/program_proof/mvcc/tuple_remove_versions.v
src/program_proof/mvcc/txnsite_deactivate.v
src/program_proof/mvcc/wrbuf_proof.v
src/program_proof/simple/setattr.v
src/program_proof/tutorial/kvservice/proof.v
src/program_proof/tutorial/queue/proof.v
src/program_proof/util_proof.v
src/program_proof/vrsm/clerk/clerk_int_proof.v
src/program_proof/vrsm/configservice/config_proof.v
src/program_proof/vrsm/replica/apply_proof.v
src/program_proof/vrsm/replica/applybackup_proof.v
src/program_proof/vrsm/replica/becomeprimary_proof.v
src/program_proof/vrsm/replica/getstate_proof.v
src/program_proof/vrsm/replica/roapply_proof.v
src/program_proof/vrsm/replica/setstate_proof.v

- After destructing an equality test, the not equals branch was not simplified. It is now turned into not equals statement over base literals.
- word can now make use of the fact that two words are not equal by deriving that their uint.Z and sint.Z values are inequal.
- `uint.Z (W64 0)` is now simplified in hypotheses, a bug that was a result of a weird implementation where 0 was handled differently from strictly positive literals.
- The addition of `; try contradiction` to `wp_if_destruct` now sometimes solves one of the branches. This isn't required by the other changes but it makes some proofs a bit nicer.
The combination of these changes mean a few scattered proofs throughout become significantly simpler, since word handles more on its own and doesn't need manual pre-processing, and …

Make wp_if_destruct and word more powerful

---

src/Helpers/Integers.v
src/goose_lang/ffi/grove_ffi/grove_ffi.v
src/goose_lang/lib/rwlock/rwlock.v
src/goose_lang/lib/rwlock/rwlock_noncrash.v
src/goose_lang/lib/slice/slice.v
src/program_proof/buf/buf_proof.v
src/program_proof/crash_lockmap_proof.v
src/program_proof/grove_shared/erpc_proof.v
src/program_proof/grove_shared/urpc_proof.v
src/program_proof/lockmap_proof.v
src/program_proof/reconf/ghost_proof.v
src/program_proof/tutorial/queue/proof.v
src/program_proof/wal/circ_proof.v
src/program_proof/wal/sliding_proof.v
src/program_proof/wal/write_proof.v

The rewrite in [word] that simplified through `uint.Z (word.add ...)` (and similar rewrites for other operations) didn't have a `repeat`, which meant that it would (sometimes) not fully rewrite through multiple operations. This is now fixed, and proofs have been updated to deal with the more powerful tactic.
Where this caused problems was when a manually written lemma was used after a `word_cleanup`, relying on the particular set of rewrites that were performed before. These were mostly in old code, and I expect new code wants a `word` tactic that is as powerful as possible.

Improve word's rewriting with a repeat

---

src/goose_lang/lib/slice/slice.v
src/goose_lang/lib/slice/typed_slice.v
src/program_proof/marshal_stateless_proof.v
src/program_proof/std_proof.v

We had several low-level specs, especially in the untyped library, but the typed library was missing many things that seem obvious in retrospect.
There are six variants based on how ownership is divided, and it makes sense to provide all of these specs since they are not obvious consequences of more general specs:
1. SliceTake with `own_slice_small`. Straightforward.
2. SliceSkip with `own_slice_small`. Straightforward.
3. SliceTake with `own_slice`. Consumes the remainder of the slice to become the capacity of the prefix. This is the most distant from the code; it is not obvious that the original slice should no longer be used, even for reads.
4. SliceSkip with `own_slice`. The capacity is retained as-is.
5. std.SliceSplit with `own_slice_small`. This is a function in the Goose standard …

Add various specs for slice skip/take

---

src/Helpers/LittleEndian.v
src/goose_lang/lang.v

Adapt to https://github.com/coq/coq/pull/19530
This is an adaptation in anticipation of the day the temporary backward compatibility introduced in the upstream PR will be removed (probably a few years in the future).
Merging this is not required for the upstream PR, you can do whatever you want with it.

Adapt to https://github.com/coq/coq/pull/19530

---

src/goose_lang/lib/slice/slice.v
src/goose_lang/lib/slice/typed_slice.v

```go
copy(dst, src[n :])
```
It seems like with the existing specifications it's not possible for `src` to retain ownership of the entire slice in the code snippet above.
The naming is not consistent with previous ones (specifically `wp_SliceCopy_subslice`), but seems more reasonable to me. Happy to rename it to `wp_SliceCopy_skip_src` or something else if people have other suggestions.

Add ownership-retaining spec for slice skip-in-copy

---

src/base_logic/lib/wsat.v

https://github.com/coq/coq/pull/19822 strengthens the unification algorithm. There is one case here where it leaves an evar uninstantiated, which breaks some typeclass search.

Adapt to coq#19822

---

external/Goose/github_com/mit_pdos/gokv/tutorial/queue.v
src/program_proof/tutorial/queue/proof.v

This is the Goose output and proof for the associated change in https://github.com/mit-pdos/gokv/pull/9. This will provide an example for how to initiate ghost state for a new HOCAP specified data structure in Perennial and removes the unnecessary handling of the slice capacity which was not being used in the original code or proof.

Add Goose code/Proof for queue new function

---

new/golang/theory/pkg.v
new/proof/grove_ffi.v

In even some simple cases this is noticeably slow without these improvements to typeclass resolution.

Speed up proving persistence of is_pkg_init

---

new/golang/defn/pkg.v
new/golang/theory/mem.v
new/golang/theory/proofmode.v
new/proof/asyncfile.v
new/proof/go_etcd_io/etcd/client/v3/concurrency.v
new/proof/lock.v
new/proof/std.v
new/proof/sync.v
src/goose_lang/ipersist.v

This automates `iMod (typed_pointsto_persist with "H") as "H"`. This works for free on struct field points-tos since they're just notation around a typed points-to. Eventually (using some typeclass instances) we can extend it to other dfrac-based propositions, like slices and ghost state, and even user `own_` propositions.
I only applied this to new goose but it could also be used in old goose just as well.
I wrote this only because I wanted to avoid remembering the name of the persistence lemma. This solution is admittedly heavyweight for that, and we could just have the typeclass and use it directly with `iMod`.

Add iPersist tactic

---

new/golang/theory.v
new/golang/theory/primitive.v
new/golang/theory/proofmode.v
new/golang/theory/slice.v
new/proof/asyncfile.v
new/proof/go_etcd_io/etcd/client/v3/concurrency.v
new/proof/go_etcd_io/etcd/client/v3/leasing.v
new/proof/std.v
src/program_proof/grove_shared/urpc_proof.v

Make proofs more natural for Fork and ArbitraryInt wp_apply didn't recognize `Fork` and `ArbitraryInt`, and they also didn't have specs using new goose's to_val.

Handle WPs for primitives better

---

new/golang/theory/auto.v
new/proof/asyncfile.v
new/proof/go_etcd_io/etcd/client/v3/leasing.v
new/proof/std.v
new/proof/sync.v
new/proof/sync_proof/mutex.v
new/proof/sync_proof/rwmutex.v
new/proof/sync_proof/rwmutex_guard.v
new/proof/sync_proof/sema.v
new/proof/sync_proof/waitgroup.v
new/proof/tok_set.v
src/Helpers/Qextra.v
src/goose_lang/lib/rwlock/rwlock.v
src/goose_lang/lib/rwlock/rwlock_derived.v
src/goose_lang/lib/rwlock/rwlock_noncrash.v

This adds specs for `RWMutex` that guard a fractional resource. This is similar to the old `rwlock.v` specs, except it limits the number of simultaneous `RLock`s and requires a token to call `RUnlock` to ensure the user does not call `RUnlock` on an already-unlocked `RWMutex`.
This also tries to more consistently put `is_pkg_init pkgname` as the first clause in the precondition of specs, which may require changes to external proofs relying on `sync.Mutex` (@tchajed ).

Specs for RWMutex

---

new/golang/theory/mem.v
new/golang/theory/slice.v
src/algebra/na_heap.v
src/goose_lang/ipersist.v
src/goose_lang/lib/typed_mem/typed_mem.v
src/goose_lang/lifting.v
src/iris_lib/dfractional.v

This is just a start. I didn't add instances for every use of Fractional, just the most basic ones. This does automatically give UpdateIntoPersistently for these definitions, which is nice and one of the original motivations here.
We could also try to fully replace Fractional with DFractional, but this would require a little more experimentation and integration with the IPM - deriving Fractional from DFractional automatically seems tricky due to higher-order unification issues.

Add a DFractional typeclass

---

new/code/github_com/goose_lang/goose/testdata/examples/unittest/generics.v
new/generatedproof/github_com/goose_lang/goose/testdata/examples/unittest/generics.v
new/proof/github_com/goose_lang/goose/testdata/examples/unittest/generics.v
new/proof/github_com/goose_lang/std.v
new/should_build.v

Adds translations from https://github.com/goose-lang/goose/pull/93 and verifies some simple specs for the new generics unit tests. This helped find a few bugs in missing support and incorrect arguments, which are hard to spot by inspection.
There are some oddities in these proofs (e.g. unexpectedly shelved instances) that aren't great but they don't seem specifically related to generics and we can debug them separately.

Verify some generics examples that now translate

---

new/golang/defn/exception.v
new/golang/theory/exception.v

As discussed in https://github.com/goose-lang/goose/pull/103, to ensure that void functions return a unit value, we can just change the default behavior of `do:` to produce a unit value, and rely on a `return:` statement if anything else should be returned. In Go reaching the end of a function without a return should produce unit for a void function, while in the case of named return values the translation already emits a `return:` as a continuation.

Change default value produced by `do:`

---

src/program_proof/grove_shared/erpc_proof.v
src/program_proof/memkv/connman_proof.v

Try to fix universe problem by making `erpc` and `connman` universe polymorphic (thereby avoiding some templated universes that resulted in inconsistent universe constraints).
Can't make `ecomp` universe polymorphic so easily: doing so makes some `ecomp` terms in `etcd/client/v3.v` no longer typecheck, possibly because typeclass inference related to `MBind` isn't working the same.

Try to fix another universe problem related to RPCs and ecomp

---

new/code/github_com/goose_lang/primitive.v
new/code/github_com/goose_lang/primitive.v.toml
new/generatedproof/github_com/goose_lang/primitive.v
new/proof/github_com/goose_lang/primitive.v
new/trusted_code/github_com/goose_lang/primitive.v

This PR also adds a model, which uses IsNoStringOverflow. See https://github.com/goose-lang/primitive/pull/2 for the code (which does nothing).

Add proof for primitive.AssumeNoStringOverflow

---

new/golang/theory/auto.v
new/golang/theory/slice.v
new/proof/github_com/goose_lang/goose/testdata/examples/unittest.v
new/proof/github_com/goose_lang/goose/testdata/examples/unittest/generics.v
new/proof/github_com/goose_lang/std.v
new/proof/github_com/goose_lang/std/std_core.v
new/proof/github_com/mit_pdos/go_journal/alloc.v
new/proof/github_com/mit_pdos/go_journal/buf_proof/buf_proof.v
new/proof/github_com/mit_pdos/go_journal/lockmap.v
new/proof/github_com/mit_pdos/go_journal/util.v
new/proof/github_com/mit_pdos/gokv/asyncfile.v
new/proof/github_com/mit_pdos/gokv/lockservice.v
new/proof/github_com/mit_pdos/gokv/partialapp.v
new/proof/go_etcd_io/etcd/client/v3/concurrency.v
new/proof/go_etcd_io/etcd/client/v3/leasing.v
new/proof/go_etcd_io/etcd/client/v3_proof/op.v
new/proof/sync_proof/cond.v
new/proof/sync_proof/rwmutex.v

This is now done in a more flexible manner so the automation can be disabled, using https://github.com/rocq-community/rocq-tricks/blob/main/src/TacticNotationOptionalParams.v.
Along the way I applied the same mechanism to give `wp_auto` a `--lc <n>` argument to optionally generate later credits.

Add back wp_auto to wp_apply

---

new/proof/github_com/goose_lang/goose/model/channel/logatom/chan_au_base.v
new/proof/github_com/goose_lang/goose/model/channel/logatom/chan_au_recv.v
new/proof/github_com/goose_lang/goose/model/channel/logatom/chan_au_send.v

Completed verification of channel receive operations (Receive, TryReceive blocking/non-blocking)
The big changes here are to support helping for unbuffered ops. A notable change is that there is now a separate inductive type for the mathematical representation and the model implementation. While these look nearly identical, the mathematical representation doesn't enter the "pending" state until the offer will be accepted, whereas the model implementation goes from idle to offer and back to idle when an offer is rescinded. 
The saved prop/pred approach allows operations to register their AUs/continuations in the mutex invariant, enabling other operations to help complete them. This is essential for select where multiple channel operations need to coordinate without premature commitment.

Verify Channel Receive Operations with Select Support

---

new/proof/github_com/goose_lang/goose/model/channel/logatom/chan_au_base.v
new/proof/github_com/goose_lang/goose/model/channel/protocol/dsp/cofe_solver_2.v
new/proof/github_com/goose_lang/goose/model/channel/protocol/dsp/dsp.v
new/proof/github_com/goose_lang/goose/model/channel/protocol/dsp/dsp_ghost_theory.v
new/proof/github_com/goose_lang/goose/model/channel/protocol/dsp/proto_model.v
new/proof/github_com/goose_lang/goose/model/channel/protocol/future/future.v
new/proof/github_com/goose_lang/goose/model/channel/protocol/handshake/handshake.v
new/proof/github_com/goose_lang/goose/model/channel/protocol/spsc/spsc.v

Add protocol/ folder with reusable invariants/specs built on the logically-atomic channel specs.
Handshake (unbuffered): proved end-to-end, simple resource exchange on unbuffered channel.
Future: Channel used as a future value, transfers a predicate P v and has 1 shot tokens called "await" and "fulfill"
SPSC : producer/consumer pipeline, has producer/consumer handles that store history and predicate P v for each value and R sent for the list at the time of close.
DSP: two goroutine endpoints/two go channels, uses Actris ghost theory. This is at an early stage but has boilerplate and some definitions/admitted lemmas.

Add protocol folder/start proving protocols
